- id: sunset_jalousien_schliessen
  alias: 'Sonnenuntergang: Jalousien und Rolladen schließen'
  trigger:
  - platform: sun
    event: sunset
  action:
  - service: cover.close_cover
    target:
      entity_id:
      - cover.wohnzimmer_jalousie_links
      - cover.wohnzimmer_jalousie_mitte
      - cover.wohnzimmer_jalousie_rechts
  - delay: 00:00:01
  - service: cover.set_cover_position
    target:
      entity_id: cover.esszimmer_jalousie
    data:
      position: 20
  - service: cover.set_cover_tilt_position
    target:
      entity_id: cover.esszimmer_jalousie
    data:
      tilt_position: 25
  - delay: 00:00:01
  - service: cover.set_cover_position
    target:
      entity_id: cover.musikzimmer_rolladen
    data:
      position: 35
  - delay: 00:00:01
  - service: cover.set_cover_position
    target:
      entity_id: cover.wc_rolladen
    data:
      position: 30
  - delay: 00:00:01
  - service: cover.set_cover_position
    target:
      entity_id: cover.buero_rolladen
    data:
      position: 20
  - delay: 00:00:01
  - service: cover.set_cover_position
    target:
      entity_id: cover.bad_rolladen
    data:
      position: 20
- id: sunrise_rolladen_oeffnen
  alias: 'Sonnenaufgang: Rolladen öffnen'
  trigger:
  - platform: sun
    event: sunrise
  action:
  - service: cover.open_cover
    target:
      entity_id:
      - cover.musikzimmer_rolladen
      - cover.wc_rolladen
      - cover.buero_rolladen
      - cover.bad_rolladen
- id: mittag_jalousien_beschatten
  alias: 'Mittagssonne: Wohnzimmer Jalousien beschatten'
  trigger:
  - platform: sun
    event: noon
  condition:
  - condition: numeric_state
    entity_id: sensor.wetter_cleebronn_cloud_coverage
    below: 75
  action:
  - service: cover.set_cover_position
    target:
      entity_id: cover.wohnzimmer_jalousie_links
    data:
      position: 20
  - service: cover.set_cover_tilt_position
    target:
      entity_id: cover.wohnzimmer_jalousie_links
    data:
      tilt_position: 40
  - service: cover.set_cover_position
    target:
      entity_id: cover.wohnzimmer_jalousie_mitte
    data:
      position: 60
  - service: cover.set_cover_tilt_position
    target:
      entity_id: cover.wohnzimmer_jalousie_mitte
    data:
      tilt_position: 40
  - service: cover.set_cover_position
    target:
      entity_id: cover.wohnzimmer_jalousie_rechts
    data:
      position: 20
  - service: cover.set_cover_tilt_position
    target:
      entity_id: cover.wohnzimmer_jalousie_rechts
    data:
      tilt_position: 45
- id: sunrise_ankleide_jalousie
  alias: 'Sonnenaufgang: Ankleide Jalousie'
  trigger:
  - platform: sun
    event: sunrise
  action:
  - choose:
    - conditions:
      - condition: numeric_state
        entity_id: sensor.wetter_cleebronn_cloud_coverage
        below: 75
      sequence:
      - service: cover.set_cover_position
        target:
          entity_id: cover.ankleide_jalousie
        data:
          position: 0
      - service: cover.set_cover_tilt_position
        target:
          entity_id: cover.ankleide_jalousie
        data:
          tilt_position: 100
    default:
    - service: cover.open_cover
      target:
        entity_id: cover.ankleide_jalousie
- id: bewegungslicht_hwr_an
  alias: 'Bewegungslicht HWR: Licht bei Bewegung an'
  triggers:
  - entity_id:
    - binary_sensor.hwr_motion_sensor_bewegung
    to:
    - 'on'
    trigger: state
  conditions:
  - condition: numeric_state
    entity_id: sensor.outdoor_hwr_motion_sensor_beleuchtungsstarke
    below: 10
  actions:
  - action: switch.turn_on
    metadata: {}
    target:
      entity_id: switch.flush_1_relay_4
    data: {}
- id: bewegungslicht_hwr_aus
  alias: 'Bewegungslicht HWR: Licht nach 20s ohne Bewegung aus'
  trigger:
  - platform: state
    entity_id: binary_sensor.hwr_sensor_motion
    to: 'off'
    for: 00:00:20
  action:
  - service: light.turn_off
    target:
      entity_id: light.hwr
- id: bewegungslicht_treppenhaus_an
  alias: 'Bewegungslicht Treppenhaus: Licht bei Bewegung an'
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.treppenhaus_sensor_oben_motion
    - binary_sensor.treppenhaus_sensor_ug_motion
    to: 'on'
  action:
  - service: light.turn_on
    target:
      entity_id: light.treppenhaus_ug
- id: bewegungslicht_treppenhaus_aus
  alias: 'Bewegungslicht Treppenhaus: Licht nach 30s ohne Bewegung aus'
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.treppenhaus_sensor_oben_motion
    - binary_sensor.treppenhaus_sensor_ug_motion
    to: 'off'
    for: 00:00:30
  condition:
  - condition: state
    entity_id: binary_sensor.treppenhaus_sensor_oben_motion
    state: 'off'
  - condition: state
    entity_id: binary_sensor.treppenhaus_sensor_ug_motion
    state: 'off'
  action:
  - service: light.turn_off
    target:
      entity_id: light.treppenhaus_ug
- id: dunkelheitslicht_aussen_an
  alias: 'Außenlicht: Blumenbeet bei Dunkelheit an'
  trigger:
  - platform: numeric_state
    entity_id: sensor.outdoor_sensor_illuminance
    below: 10
  action:
  - service: light.turn_on
    target:
      entity_id: light.hue_white_blumenbeet
- id: dunkelheitslicht_aussen_aus
  alias: 'Außenlicht: Blumenbeet bei Helligkeit aus'
  trigger:
  - platform: numeric_state
    entity_id: sensor.outdoor_sensor_illuminance
    above: 15
  action:
  - service: light.turn_off
    target:
      entity_id: light.hue_white_blumenbeet
