script:
  wohnzimmer_jalousien_auf:
    alias: "Jalousien Wohnzimmer alle öffnen"
    sequence:
      - service: number.set_value
        target:
          entity_id:
            - number.wohnzimmer_jalousie_links_tilt
            - number.wohnzimmer_jalousie_mitte_tilt
            - number.wohnzimmer_jalousie_rechts_tilt
        data:
          value: 0

      - delay:
          milliseconds: 2000

      - service: cover.open_cover
        target:
          entity_id:
            - cover.wohnzimmer_jalousie_links_cover
            - cover.wohnzimmer_jalousie_mitte_cover
            - cover.wohnzimmer_jalousie_rechts_cover


  wohnzimmer_jalousien_zu:
    alias: "Jalousien Wohnzimmer schließen"
    sequence:
      - service: cover.set_cover_position
        target:
          entity_id:
            - cover.wohnzimmer_jalousie_links_cover
            - cover.wohnzimmer_jalousie_rechts_cover
        data:
          position: 0

      - wait_template: >
          {{ is_state('cover.wohnzimmer_jalousie_links_cover', 'closed')
             and is_state('cover.wohnzimmer_jalousie_rechts_cover', 'closed') }}
        timeout:
          seconds: 60

      - service: number.set_value
        target:
          entity_id:
            - number.wohnzimmer_jalousie_links_tilt
        data:
          value: 30

      - service: number.set_value
        target:
          entity_id:
            - number.wohnzimmer_jalousie_rechts_tilt
        data:
          value: 48
