script:
  wohnzimmer_jalousien_auf:
    alias: "Jalousien Wohnzimmer alle öffnen"
    sequence:
      - service: number.set_value
        target:
          entity_id:
            - number.wohnzimmer_jalousie_links_tilt
            - number.wohnzimmer_jalousie_mitte_tilt
            - number.wohnzimmer_jalousie_rechts_tilt
        data:
          value: 100

      - delay:
          milliseconds: 2000

      - service: cover.open_cover
        target:
          entity_id:
            - cover.wohnzimmer_jalousie_links_cover
            - cover.wohnzimmer_jalousie_mitte_cover
            - cover.wohnzimmer_jalousie_rechts_cover


  wohnzimmer_jalousien_zu:
    alias: "Jalousien Wohnzimmer schließen"
    sequence:
      - service: cover.set_cover_position
        target:
          entity_id:
            - cover.wohnzimmer_jalousie_links_cover
            - cover.wohnzimmer_jalousie_rechts_cover
        data:
          position: 20   # 20 = 80% zu, wenn 0=zu und 100=offen

      - wait_template: >
          {{ state_attr('cover.wohnzimmer_jalousie_links_cover', 'current_position') | int(-1) == 20
           and state_attr('cover.wohnzimmer_jalousie_rechts_cover', 'current_position') | int(-1) == 20 }}
        timeout:
          seconds: 60

      - service: number.set_value
        target:
          entity_id:
            - number.wohnzimmer_jalousie_links_tilt
        data:
          value: 30

      - service: number.set_value
        target:
          entity_id:
            - number.wohnzimmer_jalousie_rechts_tilt
        data:
          value: 65
