template:
  - sensor:

    - name: "Solar Selfconsumption Ratio"
      unique_id: solar_selfconsumption_ratio
      icon: mdi:percent-outline
      state: >
        {% set used = (states('sensor.solar_panel_to_house_daily') | float(0))
                    + (states('sensor.solar_battery_out_daily') | float(0)) %}

        {% set total = (states('sensor.solar_panel_production_daily') | float(0)) %}

        {% if total <= 0 %}
          0
        {% else %}
          {{ (used / total * 100) | round(0) }}
        {% endif %}

    - name: "Solar Autarkie Ratio"
      unique_id: solar_autarkie_ratio
      icon: mdi:percent-outline
      state: >
        {% set cons = states('sensor.solar_house_consumption_daily') | float(0) %}
        {% set imp = states('sensor.solar_grid_imported_power_daily') | float(0) %}

        {% if cons <= 0 %}
          0
        {% else %}
          {{ ((1 - (imp / cons)) * 100) | round(0) }}
        {% endif %}

    # corr.
    - name: "Solar Inverter Effectiveness"
      unique_id: solar_inverter_effectiveness
      icon: mdi:percent-outline
      unit_of_measurement: ""
      state: >
        {% set ac = states('sensor.technikraum_solaredge_se10k_ac_power') | float(0) %}
        {% set dc = states('sensor.technikraum_solaredge_se10k_dc_power') | float(0) %}

        {% if dc < 500 or ac < 500 %}
          0.98
        {% else %}
          {% set eff = ac / dc %}
          {{ [0.85, [eff, 1.02] | min] | max }}
        {% endif %}

    # corr.
    - name: "Solar Panel Production W"
      unique_id: solar_panel_production_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:solar-power
      state: >
        {% set ac = states('sensor.technikraum_solaredge_se10k_ac_power') | float(0) %}

        {% if ac <= 0 %}
          0
        {% elif is_state('sensor.technikraum_solaredge_se10k_ac_power', 'unknown') %}
          0
        {% else %}
          {{ ac | float(0) }}
        {% endif %}

    # corr.
    - name: "Solar Panel To House W"
      unique_id: solar_panel_to_house_w
      unit_of_measurement: 'W'
      icon: mdi:solar-power
      state: >
        {% set pv = states('sensor.technikraum_solaredge_se10k_ac_power') | float(0) %}
        {% set battery = states('sensor.technikraum_solaredge_se4000h_battery1_power') | float(0) %}
        {% set grid = states('sensor.technikraum_solaredge_se4000h_m1_ac_power') | float(0) %}

        {% set house = pv - battery - grid %}

        {{ [0, house] | max }}

    # corr.
    - name: "Solar Grid To House W"
      unique_id: solar_grid_to_house_w
      unit_of_measurement: 'W'
      icon: mdi:transmission-tower-import
      state: >
        {% set grid = states('sensor.technikraum_solaredge_se4000h_m1_ac_power') | float(0) %}
        {{ [0, -grid] | max }}

    # corr.
    - name: "Solar Panel To Grid W"
      unique_id: solar_panel_to_grid_w
      unit_of_measurement: 'W'
      icon: mdi:solar-power
      state: >
        {% set grid = states('sensor.technikraum_solaredge_se4000h_m1_ac_power') | float(0) %}
        {{ [0, grid] | max }}

    # corr.
    - name: "Solar Battery To House W"
      unique_id: solar_battery_to_house_w
      unit_of_measurement: 'W'
      icon: mdi:battery-negative
      state: >
        {% set batt = states('sensor.technikraum_solaredge_se4000h_battery1_power') | float(0) %}
        {{ [0, -batt] | max }}

    # corr.
    - name: "Solar Panel To Battery W"
      unique_id: solar_panel_to_battery_w
      unit_of_measurement: 'W'
      icon: mdi:solar-power
      state: >
        {% set batt = states('sensor.technikraum_solaredge_se4000h_battery1_power') | float(0) %}
        {{ [0, batt] | max }}

    # corr.
    - name: "Solar Battery Charge W"
      unique_id: solar_battery_charge_w
      unit_of_measurement: 'W'
      icon: mdi:battery-positive
      state: >
        {% set batt = states('sensor.technikraum_solaredge_se4000h_battery1_power') | float(0) %}
        {{ [0, batt] | max }}

    # corr.
    - name: "Solar Battery Discharge W"
      unique_id: solar_battery_discharge_w
      unit_of_measurement: 'W'
      icon: mdi:battery-negative
      state: >
        {% set batt = states('sensor.technikraum_solaredge_se4000h_battery1_power') | float(0) %}
        {{ [0, -batt] | max }}

    # corr.
    - name: "Solar House Consumption W"
      unique_id: solar_house_consumption_w
      unit_of_measurement: 'W'
      icon: mdi:home
      state: >
        {% set pv = states('sensor.solar_panel_to_house_w') | float(0) %}
        {% set batt = states('sensor.solar_battery_discharge_w') | float(0) %}
        {% set grid = states('sensor.solar_grid_to_house_w') | float(0) %}

        {{ pv + batt + grid }}

    # corr.
    - name: "Solar Grid Import Power W"
      unique_id: solar_grid_import_power_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:transmission-tower-import
      state: >
        {% set m1 = states('sensor.technikraum_solaredge_se4000h_m1_ac_power') | float(0) %}
        {{ [0, -m1] | max }}

    # corr.
    - name: "Solar Grid Export Power W"
      unique_id: solar_grid_export_power_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:transmission-tower-export
      state: >
        {% set m1 = states('sensor.technikraum_solaredge_se4000h_m1_ac_power') | float(0) %}
        {{ [0, m1] | max }}

    # corr.
    - name: "Solar Lifetime Energy Production"
      unique_id: solar_lifetime_energy_production
      unit_of_measurement: 'MWh'
      icon: mdi:solar-power
      state: >
        {% set kwh = states('sensor.technikraum_solaredge_se10k_ac_energy_kwh') | float(0) %}
        {{ (kwh / 1000) | round(2) }}

sensor:
  - platform: integration
    source: sensor.solar_panel_production_w
    method: left
    unit_prefix: k
    name: solar_panel_production_kwh

  - platform: integration
    source: sensor.solar_battery_discharge_w
    method: left
    unit_prefix: k
    name: solar_battery_out_kwh

  - platform: integration
    source: sensor.solar_battery_charge_w
    method: left
    unit_prefix: k
    name: solar_battery_in_kwh

  - platform: integration
    source: sensor.solar_house_consumption_w
    method: left
    unit_prefix: k
    name: solar_house_consumption_kwh

  - platform: integration
    source: sensor.solar_grid_import_power_w
    method: left
    unit_prefix: k
    name: solar_grid_imported_power_kwh

  - platform: integration
    source: sensor.solar_grid_export_power_w
    method: left
    unit_prefix: k
    name: solar_grid_exported_power_kwh

  - platform: integration
    source: sensor.solar_panel_to_house_w
    method: left
    unit_prefix: k
    name: solar_panel_to_house_kwh

  - platform: statistics
    name: "Solar Inverter Effectiveness 24h Average"
    state_characteristic: mean
    max_age:
      hours: 24
    entity_id: sensor.solar_inverter_effectiveness


utility_meter:
  solar_panel_production_daily:
    source: sensor.solar_panel_production_kwh
    name: Solar Panel Production Daily
    cycle: daily

  solar_battery_in_daily:
    source: sensor.solar_battery_in_kwh
    name: Solar Battery In Daily
    cycle: daily

  solar_battery_out_daily:
    source: sensor.solar_battery_out_kwh
    name: Solar Battery Out Daily
    cycle: daily

  solar_house_consumption_daily:
    source: sensor.solar_house_consumption_kwh
    name: Solar House Consumption Daily
    cycle: daily

  solar_grid_imported_power_daily:
    source: sensor.solar_grid_imported_power_kwh
    name: Solar Grid Imported Power Daily
    cycle: daily

  solar_grid_exported_power_daily:
    source: sensor.solar_grid_exported_power_kwh
    name: Solar Grid Exported Power Daily
    cycle: daily

  solar_panel_to_house_daily:
    source: sensor.solar_panel_to_house_kwh
    name: Solar Panel To House Daily
    cycle: daily


  solar_panel_to_house_weekly:
    source: sensor.solar_panel_to_house_kwh
    name: Solar Panel To House Weekly
    cycle: weekly

  solar_imported_power_weekly:
    source: sensor.solar_grid_imported_power_kwh
    name: Solar Grid Imported Power Weekly
    cycle: weekly

  solar_exported_power_weekly:
    source: sensor.solar_grid_exported_power_kwh
    name: Solar Grid Exported Power Weekly
    cycle: weekly

  solar_house_consumption_weekly:
    source: sensor.solar_house_consumption_kwh
    name: Solar House Consumption Weekly
    cycle: weekly

  solar_panel_production_weekly:
    source: sensor.solar_panel_production_kwh
    name: Solar Panel Production Weekly
    cycle: weekly

  solar_battery_in_weekly:
    source: sensor.solar_battery_in_kwh
    name: Solar Battery In Weekly
    cycle: weekly

  solar_battery_out_weekly:
    source: sensor.solar_battery_out_kwh
    name: Solar Battery Out Weekly
    cycle: weekly


  solar_panel_to_house_monthly:
    source: sensor.solar_panel_to_house_kwh
    name: Solar Panel To House Monthly
    cycle: monthly

  solar_grid_imported_power_monthly:
    source: sensor.solar_grid_imported_power_kwh
    name: Solar Grid Imported Power Monthly
    cycle: monthly

  solar_grid_exported_power_monthly:
    source: sensor.solar_grid_exported_power_kwh
    name: Solar Grid Exported Power Monthly
    cycle: monthly

  solar_house_consumption_monthly:
    source: sensor.solar_house_consumption_kwh
    name: Solar House Consumption Monthly
    cycle: monthly

  solar_panel_production_monthly:
    source: sensor.solar_panel_production_kwh
    name: Solar Panel Production Monthly
    cycle: monthly

  solar_battery_in_monthly:
    source: sensor.solar_battery_in_kwh
    name: Solar Battery In Monthly
    cycle: monthly

  solar_battery_out_monthly:
    source: sensor.solar_battery_out_kwh
    name: Solar Battery Out Monthly
    cycle: monthly


  solar_panel_to_house_yearly:
    source: sensor.solar_panel_to_house_kwh
    name: Solar Panel To House Yearly
    cycle: yearly

  solar_grid_imported_power_yearly:
    source: sensor.solar_grid_imported_power_kwh
    name: Solar Grid Imported Power Yearly
    cycle: yearly

  solar_grid_exported_power_yearly:
    source: sensor.solar_grid_exported_power_kwh
    name: Solar Grid Exported Power Yearly
    cycle: yearly

  solar_house_consumption_yearly:
    source: sensor.solar_house_consumption_kwh
    name: Solar House Consumption Yearly
    cycle: yearly

  solar_panel_production_yearly:
    source: sensor.solar_panel_production_kwh
    name: Solar Panel Production Yearly
    cycle: yearly

  solar_battery_in_yearly:
    source: sensor.solar_battery_in_kwh
    name: Solar Battery In Yearly
    cycle: yearly

  solar_battery_out_yearly:
    source: sensor.solar_battery_out_kwh
    name: Solar Battery Out Yearly
    cycle: yearly
