template:
  - sensor:
    - name: "PV Selfconsumption Ratio"
      unique_id: pv_selfconsumption_ratio
      unit_of_measurement: "%"
      state_class: measurement
      icon: mdi:percent-outline
      state: >
        {% set exported = states('sensor.pv_grid_exported_power_daily') | float(0) %}
        {% set total = states('sensor.pv_panel_production_daily') | float(0) %}
        {% if total <= 0 %}
          0
        {% else %}
          {{ (((total - exported) / total) * 100) | round(0) }}
        {% endif %}

    - name: "PV Autarkie Ratio"
      unique_id: pv_autarkie_ratio
      unit_of_measurement: "%"
      state_class: measurement
      icon: mdi:percent-outline
      state: >
        {% set cons = states('sensor.pv_house_consumption_daily') | float(0) %}
        {% set imp = states('sensor.pv_grid_imported_power_daily') | float(0) %}

        {% if cons <= 0 %}
          0
        {% else %}
          {{ ((1 - (imp / cons)) * 100) | round(0) }}
        {% endif %}

    # corr.
    - name: "PV Inverter Effectiveness"
      unique_id: pv_inverter_effectiveness
      icon: mdi:percent-outline
      state_class: measurement
      unit_of_measurement: ""
      state: >
        {% set ac = states('sensor.technikraum_solaredge_se10k_ac_power') | float(0) %}
        {% set dc = states('sensor.technikraum_solaredge_se10k_dc_power') | float(0) %}

        {% if dc < 500 or ac < 500 %}
          0.98
        {% else %}
          {% set eff = ac / dc %}
          {{ [0.85, [eff, 1.0] | min] | max }}
        {% endif %}

    # corr.
    - name: "PV Panel Production W"
      unique_id: pv_panel_production_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:solar-power
      state: >
        {% set ac = states('sensor.technikraum_solaredge_se10k_ac_power') | float(0) %}
        {{ [0, ac] | max }}

    # corr.
    - name: "PV Panel To House W"
      unique_id: pv_panel_to_house_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:solar-power
      state: >
        {% set pv = states('sensor.technikraum_solaredge_se10k_ac_power') | float(0) %}
        {% set battery = states('sensor.technikraum_solaredge_se4000h_battery1_power') | float(0) %}
        {% set grid = states('sensor.technikraum_solaredge_se4000h_m1_ac_power') | float(0) %}

        {% set battery_charging = [0, battery] | max %}
        {% set grid_export = [0, grid] | max %}

        {% set panel_to_house = pv - battery_charging - grid_export %}
        {{ [0, panel_to_house] | max }}

    # corr.
    - name: "PV Grid To House W"
      unique_id: pv_grid_to_house_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:transmission-tower-import
      state: >
        {% set grid = states('sensor.technikraum_solaredge_se4000h_m1_ac_power') | float(0) %}
        {{ [0, -grid] | max }}

    # corr.
    - name: "PV Panel To Grid W"
      unique_id: pv_panel_to_grid_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:solar-power
      state: >
        {% set grid = states('sensor.technikraum_solaredge_se4000h_m1_ac_power') | float(0) %}
        {{ [0, grid] | max }}

    # corr.
    - name: "PV Battery To House W"
      unique_id: pv_battery_to_house_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:battery-negative
      state: >
        {% set batt = states('sensor.technikraum_solaredge_se4000h_battery1_power') | float(0) %}
        {{ [0, -batt] | max }}

    # corr.
    - name: "PV Panel To Battery W"
      unique_id: pv_panel_to_battery_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:solar-power
      state: >
        {% set batt = states('sensor.technikraum_solaredge_se4000h_battery1_power') | float(0) %}
        {{ [0, batt] | max }}

    # corr.
    - name: "PV Battery Charge W"
      unique_id: pv_battery_charge_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:battery-positive
      state: >
        {% set batt = states('sensor.technikraum_solaredge_se4000h_battery1_power') | float(0) %}
        {{ [0, batt] | max }}

    # corr.
    - name: "PV Battery Discharge W"
      unique_id: pv_battery_discharge_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:battery-negative
      state: >
        {% set batt = states('sensor.technikraum_solaredge_se4000h_battery1_power') | float(0) %}
        {{ [0, -batt] | max }}

    # corr.
    - name: "PV House Consumption W"
      unique_id: pv_house_consumption_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:home
      state: >
        {% set pv = states('sensor.pv_panel_to_house_w') | float(0) %}
        {% set batt = states('sensor.pv_battery_discharge_w') | float(0) %}
        {% set grid = states('sensor.pv_grid_to_house_w') | float(0) %}

        {{ pv + batt + grid }}

    # corr.
    - name: "PV Grid Import Power W"
      unique_id: pv_grid_import_power_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:transmission-tower-import
      state: >
        {% set m1 = states('sensor.technikraum_solaredge_se4000h_m1_ac_power') | float(0) %}
        {{ [0, -m1] | max }}

    # corr.
    - name: "PV Grid Export Power W"
      unique_id: pv_grid_export_power_w
      device_class: power
      state_class: measurement
      unit_of_measurement: 'W'
      icon: mdi:transmission-tower-export
      state: >
        {% set m1 = states('sensor.technikraum_solaredge_se4000h_m1_ac_power') | float(0) %}
        {{ [0, m1] | max }}

    # corr.
    - name: "PV Lifetime Energy Production"
      unique_id: pv_lifetime_energy_production
      unit_of_measurement: 'MWh'
      icon: mdi:solar-power
      state: >
        {% set kwh = states('sensor.technikraum_solaredge_se10k_ac_energy_kwh') | float(0) %}
        {{ (kwh / 1000) | round(2) }}
