utility_meter:
  pv_panel_production_daily:
    source: sensor.technikraum_solaredge_se10k_ac_energy_kwh
    name: PV Panel Production Daily
    cycle: daily
  pv_panel_production_weekly:
    source: sensor.technikraum_solaredge_se10k_ac_energy_kwh
    name: PV Panel Production Weekly
    cycle: weekly
  pv_panel_production_monthly:
    source: sensor.technikraum_solaredge_se10k_ac_energy_kwh
    name: PV Panel Production Monthly
    cycle: monthly
  pv_panel_production_yearly:
    source: sensor.technikraum_solaredge_se10k_ac_energy_kwh
    name: PV Panel Production Yearly
    cycle: yearly


  pv_grid_imported_power_daily:
    source: sensor.technikraum_solaredge_se4000h_m1_imported_kwh
    name: PV Grid Imported Power Daily
    cycle: daily
  pv_grid_imported_power_weekly:
    source: sensor.technikraum_solaredge_se4000h_m1_imported_kwh
    name: PV Grid Imported Power Weekly
    cycle: weekly
  pv_grid_imported_power_monthly:
    source: sensor.technikraum_solaredge_se4000h_m1_imported_kwh
    name: PV Grid Imported Power Monthly
    cycle: monthly
  pv_grid_imported_power_yearly:
    source: sensor.technikraum_solaredge_se4000h_m1_imported_kwh
    name: PV Grid Imported Power Yearly
    cycle: yearly


  pv_grid_exported_power_daily:
    source: sensor.technikraum_solaredge_se4000h_m1_exported_kwh
    name: PV Grid Exported Power Daily
    cycle: daily
  pv_grid_exported_power_weekly:
    source: sensor.technikraum_solaredge_se4000h_m1_exported_kwh
    name: PV Grid Exported Power Weekly
    cycle: weekly
  pv_grid_exported_power_monthly:
    source: sensor.technikraum_solaredge_se4000h_m1_exported_kwh
    name: PV Grid Exported Power Monthly
    cycle: monthly
  pv_grid_exported_power_yearly:
    source: sensor.technikraum_solaredge_se4000h_m1_exported_kwh
    name: PV Grid Exported Power Yearly
    cycle: yearly


  pv_panel_to_house_daily:
    source: sensor.pv_panel_to_house_kwh
    name: PV Panel To House Daily
    cycle: daily
  pv_panel_to_house_weekly:
    source: sensor.pv_panel_to_house_kwh
    name: PV Panel To House Weekly
    cycle: weekly
  pv_panel_to_house_monthly:
    source: sensor.pv_panel_to_house_kwh
    name: PV Panel To House Monthly
    cycle: monthly
  pv_panel_to_house_yearly:
    source: sensor.pv_panel_to_house_kwh
    name: PV Panel To House Yearly
    cycle: yearly


  pv_house_consumption_daily:
    source: sensor.pv_house_consumption_kwh
    name: PV House Consumption Daily
    cycle: daily
  pv_house_consumption_weekly:
    source: sensor.pv_house_consumption_kwh
    name: PV House Consumption Weekly
    cycle: weekly
  pv_house_consumption_monthly:
    source: sensor.pv_house_consumption_kwh
    name: PV House Consumption Monthly
    cycle: monthly
  pv_house_consumption_yearly:
    source: sensor.pv_house_consumption_kwh
    name: PV House Consumption Yearly
    cycle: yearly


  pv_battery_in_daily:
    source: sensor.pv_battery_in_kwh
    name: PV Battery In Daily
    cycle: daily
  pv_battery_in_weekly:
    source: sensor.pv_battery_in_kwh
    name: PV Battery In Weekly
    cycle: weekly
  pv_battery_in_monthly:
    source: sensor.pv_battery_in_kwh
    name: PV Battery In Monthly
    cycle: monthly
  pv_battery_in_yearly:
    source: sensor.pv_battery_in_kwh
    name: PV Battery In Yearly
    cycle: yearly


  pv_battery_out_daily:
    source: sensor.pv_battery_out_kwh
    name: PV Battery Out Daily
    cycle: daily
  pv_battery_out_weekly:
    source: sensor.pv_battery_out_kwh
    name: PV Battery Out Weekly
    cycle: weekly
  pv_battery_out_monthly:
    source: sensor.pv_battery_out_kwh
    name: PV Battery Out Monthly
    cycle: monthly
  pv_battery_out_yearly:
    source: sensor.pv_battery_out_kwh
    name: PV Battery Out Yearly
    cycle: yearly
